import feedparser
import google.generativeai as genai
import os

def main():
    api_key = os.environ.get("GEMINI_API_KEY")
    genai.configure(api_key=api_key)
    
    try:
        models = [m.name for m in genai.list_models() if 'generateContent' in m.supported_generation_methods]
        target_model = models[0] if models else 'gemini-1.5-flash'
    except:
        target_model = 'gemini-1.5-flash'

    model = genai.GenerativeModel(target_model)
    
    # 精選高階新聞源，確保內容具備學術深度
    feeds = [
        "https://www.economist.com/international/rss.xml",
        "https://foreignpolicy.com/feed/",
        "https://api.quantamagazine.org/feed/"
    ]
    
    news_text = ""
    for url in feeds:
        try:
            f = feedparser.parse(url)
            for entry in f.entries[:2]: # 每個來源抓取更多素材
                news_text += f"Headline: {entry.title}\nContext: {entry.summary}\n\n"
        except: continue

    # 針對你的需求優化 Prompt：全英文指令，針對 FLPT 衝刺，僅單字釋義保留中文輔助
    prompt = f"""
    Target: FLPT Level C1+ (Score 240+).
    Input Materials: {news_text}
    
    Task: Create a cohesive C1 academic analysis based on these materials. Structure your response in a news magazine format.

    Part 1: [The Deep Read - 深度閱讀]
    Write ONE contiguous 500-word academic analysis. The text should have proper paragraph breaks (at least 3-4 paragraphs), logically transitioning between introduction, arguments, and conclusion. 
    - Use sophisticated C1 vocabulary and sentence structures (inversion, subjunctive mood, nominalization).

    Part 2: [Analysis - 文章解析]
    - Summary (English): 3 concise bullet points.
    - Structural Analysis (Traditional Chinese): Explain how the essay is logically built.

    Part 3: [The Vocabulary Bank - 核心詞彙]
    List 8 academic terms or idioms with definitions and Traditional Chinese meaning.

    Part 4: [FLPT Inference Quiz - 模擬測驗]
    - 2 Multiple-choice questions. DO NOT ask for facts; ask for the IMPLIED meaning.
    - Provide answers and explanations (Traditional Chinese).
    """
    
    try:
        response = model.generate_content(prompt)
        content = response.text
        
        with open("Daily_Study.md", "w", encoding="utf-8") as f:
            f.write(content)
            
        # 轉換成 HTML 並應用《紐約時報》排版
        # 我們自定義了一個 CSS 樣式表來達到襯線字體和柔和色彩的排版
        display_content = content.replace('# ', '<h1>').replace('## ', '<h2>').replace('\n', '<br>')
        
        html_template = """
        <!DOCTYPE html>
        <html>
        <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>C1 Advanced: Academic Immersion</title>
            <style>
                /* 《紐約時報》風格 CSS 開發 */
                body {{
                    font-family: 'NYTCheltenham', 'Georgia', 'serif'; /* 使用襯線字體提升閱讀體驗 */
                    line-height: 1.8; /* 增加行距，降低閱讀壓力 */
                    color: #121212; /* 使用深灰色而非純黑，更護眼 */
                    background-color: #fdfdfd; /* 微米色背景，模仿紙張質感 */
                    margin: 0;
                    padding: 0;
                    box-sizing: border-box;
                }}
                .container {{
                    max-width: 720px; /* 限制寬度，更符合人類視線掃描範圍 */
                    margin: 0 auto;
                    padding: 40px 20px;
                }}
                h1 {{
                    font-family: 'NYTImperial', 'Georgia', serif;
                    font-size: 2.5em;
                    color: #121212;
                    text-align: center;
                    margin-bottom: 30px;
                }}
                h2 {{
                    font-size: 1.2em;
                    text-transform: uppercase;
                    color: #003366; /* 使用優雅的深藍色作為標題色 */
                    letter-spacing: 0.1em;
                    margin-top: 50px;
                    border-bottom: 1px solid #ddd;
                    padding-bottom: 5px;
                }}
                .academic-text {{
                    font-size: 1.15em;
                    color: #262626;
                }}
                .markdown-body {{
                    box-sizing: border-box;
                    min-width: 200px;
                    max-width: 980px;
                    margin: 0 auto;
                    padding: 45px;
                }}
                @media (max-width: 767px) {{
                    .container {{ padding: 20px 10px; }}
                    h1 {{ font-size: 1.8em; }}
                }}
            </style>
        </head>
        <body class="markdown-body">
            <div class="container academic-text">
                <div style="text-align:right; font-weight:bold; color:#003366;">FLPT 240+ Daily</div>
                {article}
                <hr>
                <footer style="text-align:center; color:#666; font-size:0.9em; margin-top: 50px;">
                    Generated by Gemini AI for startchao | Aim for FLPT 240+ | Styled with respect to NYT
                </footer>
            </div>
        </body>
        </html>
        """
        
        with open("index.html", "w", encoding="utf-8") as f:
            f.write(html_template.format(article=display_content))
            
    except Exception as e:
        print(f"Error: {e}")

if __name__ == "__main__":
    main()
