import feedparser
import google.generativeai as genai
import os

def main():
    # 讀取新 Key
    api_key = os.environ.get("GEMINI_API_KEY")
    genai.configure(api_key=api_key)
    
    # 自動尋找可用的生成模型（徹底解決 404 問題）
    try:
        models = [m.name for m in genai.list_models() if 'generateContent' in m.supported_generation_methods]
        target_model = models[0] if models else 'models/gemini-1.5-flash'
    except:
        target_model = 'gemini-1.5-flash'

    model = genai.GenerativeModel(target_model)
    
    # 抓取新聞
    news_feed = feedparser.parse("https://www.cisa.gov/cybersecurity-alerts.xml")
    news_text = "\n".join([f"{e.title}: {e.summary}" for e in news_feed.entries[:3]])
    
    prompt = f"Role: C1 English Tutor. Use this news: {news_text}. Task: Rewrite in C1 level English, provide 5 academic vocabs, 1 grammar point, and 2 quiz questions. Use Traditional Chinese for explanations."
    
    try:
        response = model.generate_content(prompt)
        with open("Daily_Study.md", "w", encoding="utf-8") as f:
            f.write(f"Generated by: {target_model}\n\n" + response.text)
    except Exception as e:
        with open("Daily_Study.md", "w", encoding="utf-8") as f:
            f.write(f"AI Error: {str(e)}")

if __name__ == "__main__":
    main()
